spec/models/multiresimage_spec.rb
this is a really small change. We had to update the 'fixture' that we're comparing against. We had the incorrect value before, the file path fragment is what Images is expecting
=> fixing the file location in the spec

app/assets/stylesheets/dil.css, app/views/catalog/_document.html.erb, app/views/catalog/_home_text.html.erb, app/views/dil_collections/_members.html.erb
Took out some Bootstrap 2 workarounds and improved the image group items markup a bit.
=> Update styling for homepage, catalog and image groups to Bootstrap 3

app/models/multiresimage.rb, app/models/svg_datastream.rb, app/models/vra_datastream.rb, app/models/vrawork.rb, spec/models/multiresimage_spec.rb, spec/support/matchers/match_xml_except.rb
we weren't actually creating vra work records from the image record, but now we are! side bonus: this now fixes all the multiresimage specs (and i got rid of some deprecation warnings)
=> Fix vra works

app/views/multiresimages/_related_images.html.erb
=> fixing the thumbnails for related images

Gemfile, Gemfile.lock
i didn't update every gem to the latest version, but therubyracer, cancan, and omniauth-ldap are updated! hopefully
=> removing version locking for the last several gems, and updating those

Gemfile, Gemfile.lock, app/controllers/multiresimages_controller.rb, app/views/multiresimages/show.html.erb
most of the edit stuff has already been removed, but here's some more that needs to get removed
i also removed the dotenv gem since we're using the secrets.yml file instead
=> Remove edit

app/models/multiresimage.rb, app/models/vra_datastream.rb
this branch is for DIL-4429 , it adds the title to the relationset display and the relation itself. 
There aren't any tests for this because i'm not sure how we'd test it, but all the existing tests pass and i ran through a publish from menu -> Images and it worked correctly. So we can talk about it!
=> Relation title

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, config/routes.rb
moving the about_page gem so it's only loaded in dev/stage
also changed the title of the app from DIL -> Images|Repository
=> About page prod

lib/xslt/marc2vra.xsl
=> updating the xslt to jyo's latest version

Capfile, Gemfile, Gemfile.lock, config/application.rb, config/deploy.rb, config/deploy/production.rb, config/deploy/remote_dev.rb, config/deploy/staging.rb, config/initializers/about_page.rb, config/routes.rb
=> Better gem organization

app/models/dil_collection.rb, app/views/dil_collections/generate_powerpoint.js.erb
Fixes #147
This PR requires the updated dil-config.yml which now includes 'base_url' for each environment.
Use the new riiif image-service url for generating PPT files. Fixes a bug in the polling javascript so the polling stops when the PPT generation succeeds.
* Updated PPT generation code
* Bugfix in js polling
=> 147 update ppt

Gemfile
=> switched pry group, apparently its needed in stage

app/controllers/multiresimages_controller.rb
Need to return head from MultiresimagesController#update_vra action, otherwise Rails looks for a template to render.
=> Return head :ok in MultiresimagesController#update_vra

app/controllers/batches_controller.rb, app/models/multiresimage.rb, app/workers/multiresimages_batch_worker.rb
Swap out single job batches for individual image creation.
=> Individual image batches

app/controllers/institutional_collections_controller.rb
Fixes #159 
The InstitutionalCollections controller authenticates and authorizes only admins for any action.
=> InstitutionalCollections controller for admins only

app/controllers/catalog_controller.rb, config/initializers/load_dil_configs.rb, config/initializers/mime_types.rb
This branch reduces the number of deprecation warnings we see when running in dev. This should clean up our logs a bit and make it a bit nicer to visually parse messages
=> Reduce deprecations

Gemfile, Gemfile.lock
Fixes #219  
Switches from sidekiq to sidekiq pro
We'll need to run a bundle config command on our servers as the deploy user so we are authorized to run sidekiq pro, but we'll handle that off of github
=> changing to sidekiq pro

config/routes.rb
=> adding pro routes

app/views/catalog/_home_text.html.erb
Addresses #308 
Reducing the number of fedora calls may improve speed.
=> Improve homepage performance

app/models/vra_datastream.rb
Fixes #294
Uses the content of (each) style period for facets, rather than the style period display text.
=> Add a facet for each style period

app/controllers/multiresimages_controller.rb, app/models/vra_datastream.rb
Fixes #293 ; Fixes #294 
Update index on image after updating VRA. Also, set style period facet to each style period rather than display.
=> Addresses issues with facet content and display

app/controllers/multiresimages_controller.rb, app/views/multiresimages/_downloads.html.erb, config/routes.rb
refs #291 
Handles error and displays message if TIF file not found or there is an error retrieving it.
=> 291 tif download error handling

lib/tasks/wipeout.rake
a quick port of avalon's wipeout rake task
=> added a lightly modified avalon wipeout task

Gemfile.lock, app/helpers/image_mover.rb, config/deploy.rb, config/deploy/staging.rb
Updating image mover to accept tif and tiff inputs
=> Update image mover
