nulib/images

- db/migrate/20150212175935_remove_uploads_table.rb
- db/migrate/20150212180547_remove_image_processing_requests.rb
- db/schema.rb
these tables are related to the upload images feature, which we're not using anymore
Remember that you'll need to run a rake db:migrate !!!!!
> create migrations to drop tables related to removed features

- app/controllers/batches_controller.rb
- app/helpers/transform_xml.rb
- app/models/image_mover.rb
- app/models/multiresimage.rb
- spec/rails_helper.rb
Fixes #180 
This PR removes extraneous calls to the Sidekiq logger.
* app/controllers/batches_controller.rb
* app/helpers/transform_xml.rb
* app/models/image_mover.rb
* app/models/multiresimage.rb
* spec/rails_helper.rb
> Removing calls to Sidekiq::Logging.logger

- app/controllers/multiresimages_controller.rb
- app/models/multiresimage.rb
- app/workers/multiresimages_batch_worker.rb
- config/application.rb
- spec/controllers/batches_controller_spec.rb
- spec/controllers/multiresimages_controller_spec.rb
- spec/models/multiresimage_spec.rb
Fixes #187
A first pass at cleaning up the unused clutter in the Multiresimage model and controller.
* Refactor #create_archv_techmd_datastream and #create_jhove_xml (unused variables)
* Remove unused methods
* Remove extraneous comments
* Clean up spacing and indentation
> Clean up Multiresimage model, refactor jhove creation

- app/controllers/technical_metadata_controller.rb
Fixes #203 
Opens VRA endpoint to the world
go to http://localhost:3331/technical_metadata/inu:dil-af3c7e97-8fee-4a3d-8584-913fd3089c92/VRA (locally) and see VRA regardless of authentication status
> working vra endpoint with a bit of authorization

- app/models/multiresimage.rb
Fixes #178 
Document the fact that we no longer create JP2 datastreams in the Multiresimage model.
> Move deprecated datastreams to comment section

- app/views/institutional_collections/images.html.erb
Fixes #171 
Thumbnails work with the latest helper for the riiif image_service.
> Use new helper for riiif images

- app/controllers/institutional_collections_controller.rb
- app/models/institutional_collection.rb
- app/views/catalog/_home_text.html.erb
- app/views/institutional_collections/_form.html.erb
- config/predicate_mappings.yml
- spec/models/institutional_collection_spec.rb
Fixes #157 
Replaces current representative_member attribute in InstitutionalCollection objects with a thumbnail_url property (stored as a string). Modifies the Institutional Collection form to include a text area where a url can be supplied for an existing multiresimage. Thumbnails on the landing page then use this url to generate images for each collection.
> Add a thumbnail_url property on InstitutionalCollections

- app/controllers/institutional_collections_controller.rb
- app/models/multiresimage.rb
- app/views/_user_util_links.html.erb
- app/views/institutional_collections/add_images.html.erb
- app/views/institutional_collections/index.html.erb
- app/workers/add_institutional_collection_worker.rb
- app/workers/remove_institutional_collection_worker.rb
Fixes #259 
Sidekiq workers are used for adding images to an institutional collection and for deleting institutional collections. Images are re-associated with the DIL Collection before the institutional collection is deleted.
* app/workers/add_institutional_collection_worker.rb
* app/workers/remove_institutional_collection_worker.rb
* links to institutional collections index page and sidekiq dashboard added to navigation for admins only
> 259 institutional collection workers

- app/controllers/institutional_collections_controller.rb
- app/workers/add_institutional_collection_worker.rb
Fixes #271
Jobs that add images to a collection can now be viewed as a Batch in the Sidekiq interface.  Check the "Batches" Tab in Sidekiq when you add images to a collection.
> Update add images to collection to use batches

- config/routes.rb
Fixes #273 
Fixes issue where Sidekiq Dashboard was open to all authenticated Northwestern Users.
(Test with non-admin user credentials)
> Sidekiq web route admin only

- app/helpers/dil_blacklight/solr_helpers/object_type_facet.rb
Fixes #258 
Catalog search results are letting in Vrawork records. This PR adds an :fq filter in the DIL_Blacklight::SolrHelpers::ObjectTypeFacet module to remove them.
*  app/helpers/dil_blacklight/solr_helpers/object_type_facet.rb
> Filter Vrawork records out of search results

- app/helpers/image_mover.rb
- app/models/multiresimage.rb
tifs need to be renamed to pid.tif when they are moved to repository
> rename tiffs when they are moved

- config/deploy.rb
This should stop the riiif cache from being invalidated on every deploy
> adding tmp/cache to shared directories

- app/views/catalog/_home_text.html.erb
- app/views/institutional_collections/rights.html.erb
Fixes #302 
Changes to two views so that popup on homepage now shows description of collection as well as the rights description. To test go to homepage and click "About this Collection".
> Add collection description to popup on homepage

- app/controllers/multiresimages_controller.rb
Fixes #293
After editing an image record in Menu, both the old and new facet values remain in solr. (for example, the agent_name_facet, (which displays as Creator on the website). Adding an update index after the edit appears to address the issue.
> Update solr index for image after edit in menu

- app/controllers/multiresimages_controller.rb
- app/models/vra_datastream.rb
Fixes #293 
Fixes #294 
Fixes #338 
Addresses an issue where Style Period facet was displaying display text rather than style periods, and an issue where when facets were updated, the old value was being retained in the solr doc.
> 293 reindexing facets

- app/controllers/multiresimages_controller.rb
- app/views/multiresimages/_downloads.html.erb
Fixes #291 
A button to download the tif will be displayed for logged in admin users.
> Allow admins to download archival tiffs for all images

- app/controllers/multiresimages_controller.rb
- app/views/multiresimages/_downloads.html.erb
- config/environments/staging.rb
- lib/tasks/wipeout.rake
Fixes #291 
Fixes #344 
Admins will see a button to download the archival image (tif) for every multiresimage. 
Also contains rake task to wipe data from Solr/Fedora instance.
> Admin TIF Download

- app/helpers/transform_xml.rb
- app/models/multiresimage.rb
- app/models/vrawork.rb
- app/validators/vra_validator.rb
- app/workers/multiresimages_batch_worker.rb
Fixes #350 
Currently, if display elements are provided, the Images application is duplicating the display element  and creating invalid VRA. 
Fixes #347 
Currently, if a batch ingest record fails at specific points an orpahned VRAWork record is created in Images. This causes subsequent retries to fail with: `Existing image found with this accession number:`
Documentation for batch ingest (VRA) xml input requirement, xml transformations and validations for the Images application:
* [https://github.com/nulib/images/wiki/Batch-Ingest-Input-VRA-XML](https://github.com/nulib/images/wiki/Batch-Ingest-Input-VRA-XML)
**Changes proposed in this pull request:**
* Fixes bugs in validation check of VRA against the schema (both work and image), after it is transformed during a batch ingest of an …
> 350 vra display elements

- app/controllers/institutional_collections_controller.rb
- app/views/institutional_collections/show.html.erb
- config/routes.rb
For convenience, a button is located on the InstitutionalCollection#show pages as well.
> Add an endpoint that renders a list of member pids as text

- app/views/institutional_collections/_form.html.erb
Small change to the institutional collection edit form, making the collection description field a text area instead of a text field.
> Make collection description field a text area

- app/models/multiresimage.rb
- app/workers/multiresimages_batch_worker.rb
- config/sidekiq.yml
The main changes in this PR are removing the need to copy the original tiff to another location so we can create a derivative of it and getting rid of some of the extraneous checks and ensures.
> cleaned up batch worker to make the logic a bit more straight forward
